{% set name = "flake8-unused-arguments" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flake8-unused-arguments-{{ version }}.tar.gz
  sha256: c5894d294424bf7915e44dff0917222c454151016f96edc55b9f847bf307f3f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - flake8 >3.0.0

test:
  imports:
    - flake8_unused_arguments
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nhoad/flake8-unused-arguments
  summary: flake8 extension to warn on unused function arguments
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - santisoler
